name: CI Pipeline

on:
  push:
    branches: [ main ]

jobs:
  security:          # 👈 NUEVO job de seguridad
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Analisis SAST con CodeQL
        uses: github/codeql-action/analyze@v2

  test:
    runs-on: ubuntu-latest
    needs: security   # 👈 los tests solo corren si seguridad pasa
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install
      - run: npm test